### ISSUE TITLE
proposal: move attributes nodes to html/attribute

### ISSUE THREAD

**Issue by SirMetathyst** [maragudk/gomponents#122]
Tbh the Attr and El suffixes bother me alot. What do you think about moving attributes to /html/attribute package and removing the suffixes, You can then just use a regular import and use `a.MyAttribute` I did not look into this much as I only just found this library but it's something which stood out and annoyed me...

**Comment by markuswustenberg** [comment]
I had that originally. Then you can't dot-import both packages unfortunately, because you'll have the name clash again.

(And it would be a big breaking change.)

**Comment by SirMetathyst** [comment]
Dot-imports shouldn't be used anyway although I'm sure many out there like them (Perhaps yourself?). It's an opinionated subject, just like my dislike for the `El` and `Attr` suffixes. It sounds like you don't want to make this change (back) so I will close this issue due to incompatible opinion.
