### ISSUE TITLE
performance benchmarks

### ISSUE THREAD

**Issue by SirMetathyst** [maragudk/gomponents#123]
Are there any performance benchmarks: speed / memory usage etc in comparison to libraries like Valyala's QuickTemplate (which I consider one of the fastest template libraries for go out there which I know of, representing the "top" performing template engine) and Go standard template/html?

**Comment by markuswustenberg** [comment]
Nope, I don't have that. I care much more about API design and developer experience, to be honest. 😊 Compared to network I/O, I don't think it matters much anyway.

There are some benchmarks you can run in the library, but they're more there to check I haven't done anything stupid while refactoring than for comparison with other libraries.

**Comment by SirMetathyst** [comment]
Would you be willing to accept a PR which included benchmark comparisons and the code to execute them?

**Comment by markuswustenberg** [comment]
No, I think it's outside the scope of the repository, and not something I want to highlight as a feature, for the aforementioned reasons.

It sounds like a good separate repository that draws in several other libraries and does the comparisons, like people do for other kinds of libraries in the Go ecosystem.

**Comment by SirMetathyst** [comment]
Alright. Thank you for your time.

**Comment by markuswustenberg** [comment]
And thank you for your offer! 😊
