### ISSUE TITLE
Is output escaped?

### ISSUE THREAD

**Issue by TheManSpeaker** [maragudk/gomponents#133]
Hello, interested in using this library for my next project - I had a question that I didn’t see an answer to in the documentation (unless I missed it somewhere): is the output escaped/sanitized to prevent XSS when outputting untrusted user input? Or is that something the user of this library would need to do manually?

**Comment by TheManSpeaker** [comment]
I think I answered my own question by digging into the source code, it looks like g.Text() does this

**Comment by TheManSpeaker** [comment]
Wanted to add, thanks for creating this! It looks awesome, much better than using templates!

**Comment by markuswustenberg** [comment]
Hi @TheManSpeaker , thank you for your feedback and the kind words! 😊

I'm curious, where did you look for the information first? Dove right into the source? Maybe I can improve how information like that can be found.

**Comment by TheManSpeaker** [comment]
@markuswustenberg I first checked the website https://www.gomponents.com/, and also checked the README on the github repo https://github.com/maragudk/gomponents. When I didn't see it mentioned either of those places, then I dug into the source and found my answer there (after opening this issue)

I think a good place to add mention of this might be in the "Features" section https://github.com/maragudk/gomponents#features.. something like "Automatically sanitizes HTML output from untrusted user input using the `Text()` function" or something along those lines (wording probably needs some work)

**Comment by markuswustenberg** [comment]
@TheManSpeaker thank you again. I've adjusted the readme and package docs to hopefully make things a bit clearer. 😊
