### ISSUE TITLE
Fragments

### ISSUE THREAD

**Issue by TheManSpeaker** [maragudk/gomponents#140]
I think it would be helpful to have a `Fragment` function that outputs the children with no actual parent element (similar to React.Fragment https://legacy.reactjs.org/docs/fragments.html)

This would be useful in scenarios where you need to spread a slice into an element like this - but don't actually want to wrap it in a `<div />` tag
```go
Body: []g.Node{
	content,
	html.Div(modals...),
	html.Script(
		html.Src("https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"),
		g.Attr("integrity", "sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"),
		g.Attr("crossorigin", "anonymous"),
	),
},
```

**Comment by markuswustenberg** [comment]
@TheManSpeaker thank you for your issue submission. 😊 I think maybe the [Group](https://pkg.go.dev/github.com/maragudk/gomponents#Group) function is what you're looking for? Or is it slightly different?

**Comment by TheManSpeaker** [comment]
Ah yes that’s exactly what I need, thank you!

**Comment by markuswustenberg** [comment]
Excellent, good to hear.

**Comment by niklasgrewe** [comment]
@markuswustenberg in my case the `g.group` func doesn't fit very well. I try to set my components like this:

```go
func HomePage() g.Node {
   return g.Group(
      Component("1"),
      Component("2"),
   ),
}
```

**Comment by markuswustenberg** [comment]
> @markuswustenberg in my case the `g.group` func doesn't fit very well. I try to set my components like this:
> 
> 
> 
> ```go
> 
> func HomePage() g.Node {
> 
>    return g.Group(
> 
>       Component("1"),
> 
>       Component("2"),
> 
>    ),
> 
> }
> 
> ```

You could either wrap the parameters in a Node slice or use a Div (or other such components). Often it's a matter of dividing the components differently so that you include the root of your subcomponent in the function return. How does that work for you?

**Comment by taylorkline** [comment]
> > [@markuswustenberg](https://github.com/markuswustenberg) in my case the `g.group` func doesn't fit very well. I try to set my components like this:
> > func HomePage() g.Node {
> > 
> >    return g.Group(
> > 
> >       Component("1"),
> > 
> >       Component("2"),
> > 
> >    ),
> > 
> > }
> 
> You could either wrap the parameters in a Node slice or use a Div (or other such components). Often it's a matter of dividing the components differently so that you include the root of your subcomponent in the function return. How does that work for you?

I am not the original person you replied to, but this was very helpful - thank you!
