### ISSUE TITLE
Links?

### ISSUE THREAD

**Issue by delaneyj** [maragudk/gomponents#141]
You have Heroicons, HTMX, etc but not shown on main site.

Also I made a set of basically every icon available https://github.com/delaneyj/gomponents-iconify which is a super set of your Heroicons.

**Comment by markuswustenberg** [comment]
Hi @delaneyj,

thanks for your input! They are actually linked at https://www.gomponents.com/plus/ . I'd be happy to link to your icon set as well. 😊 I'll let you know when I've done that.
