### ISSUE TITLE
Why g.Map doesn't also do g.Group?

### ISSUE THREAD

**Issue by alarbada** [maragudk/gomponents#143]
I mean, I get it that the common map operation should return a slice.

Could we also have maybe a g.ForEach that does both operations at once?

By the way, really nice idea! This plays really really well with htmx.

**Comment by markuswustenberg** [comment]
Hi @alarbada, thank you for taking the time to file an issue. 😊 I’m currently on paternity leave and will have a look at this with some delay.

**Comment by markuswustenberg** [comment]
Hi @alarbada . Thank you for your patience!

Sometimes, you need the slice itself, so I think having the `Map` and `Group` operations separate makes sense. I think adding another similar-sounding function would be a bit confusing, and I'd rather not make the API surface larger than necessary. I would recommend you add a tiny helper function in your view package and use that:

```go
func MapGroup[T any](ts []T, cb func(T) Node) Node {
    return g.Group(g.Map(ts, cb))
}
```
