### ISSUE TITLE
Use Custom attributes & alpine js

### ISSUE THREAD

**Issue by CherphAlt** [maragudk/gomponents#146]

**Comment by markuswustenberg** [comment]
@CherphAlt you'll have to be a bit more specific with what this issue means. 😊

**Comment by CherphAlt** [comment]
How can i add custom attributes to the html elements like data-this or use custom elements

**Comment by markuswustenberg** [comment]
Have a look at the docs at https://pkg.go.dev/github.com/maragudk/gomponents#Attr .
