### ISSUE TITLE
Merge multiple occurrences of the `class` attribute

### ISSUE THREAD

**Issue by tbe** [maragudk/gomponents#150]
Currently, `html.Class` and `components.Classes` each render to an own `class=[...]` attribute.

While this should be fine for most cases, there scenarios where this is an issue.

For a simple example, here is a BulmaCSS based button component:

```go
func BulmaButton(children ...g.Node) g.Node {
    return Button(Class("button"), g.Group(children))
}
```

Using this component works as expected with most attributes, but if one would like to declare this button as primary, the class attribute occours multiple times, and this will result in invalid HTML5

```go
BulmaButton(Class("is-primary",g.Text("My Button"))
```

Would render to
```html
<button class="button" class="is-primary">My Button</button>
```

To fix this, all direct children of an element must be inspected, to check for all attributes, that would render to child, and merge them into a single attribute. Sounds easy, but it look rather complicated, as we have (nested) groups: https://github.com/maragudk/gomponents/blob/main/gomponents.go#L76

I'm willing to provide this feature, but i would like to hear your opinion first. My idea would be to flatten those attribute groups first, then iterate over them to find all that render to `class` and merge them. After that, the normal rendering process could resume.  This sounds a little hacky to me, and will likely result in some impact to the rendering time, but other solutions would require more, deep, changes in the whole way how attributes work.

**Comment by markuswustenberg** [comment]
Hi @tbe, thank you for your contribution!

I actually like the way that the library is "dumb" in the way that, if you provide it with invalid HTML, it will happily render that, just like if you wrote raw HTML. However, I see your point.

I think in your case it would make sense to bake the `is-primary` functionality into the button itself:

```go
type BulmaButtonProps struct {
    IsPrimary bool
}

func BulmaButton(p BulmaButtonProps, children ...g.Node) g.Node {
    return Button(c.Classes{"button": true, "is-primary": p.IsPrimary}, g.Group(children))
}
```

So basically the button "owns" the various ways in which it can be rendered. Would that solution solve your issue?

**Comment by tbe** [comment]
Hey @markuswustenberg , that is the exact usecase why i open this issue.
While "dump" rendering is fine if you use the gomponents directly, in this case it is not obvious to a user what happens. If the user provides another set of classes, the "is-primary" will be shadowed, or it will shadow the user supplied classes, however the browser decides.

As the type of the attributes is not exported, we can't apply any check in the factory function for the button.

**Comment by markuswustenberg** [comment]
Yes, that's true, there can be attribute clashes in general. I think there's no way around that in gomponents because of the way I've designed it. Solutions that I can currently think of:

1. Document that the user of the `BulmaButton` shouldn't use separate `class` attributes.
2. Don't accept arbitrary `Node` children but only custom types.
3. Put children nodes on a child node of the button and not the button directly, thus creating a sort of wrapper node inside the button.
4. Render all children nodes and check for disallowed attributes.

Would any of those work in your use case?

**Comment by tbe** [comment]
After thinking about it, i see your concerns. My needs differ from the design philosophy behind gomponents. So i decided to write an alternative module, that sacrifices a little bit of usability for more advanced features. Should hit github today or tomorrow.

The main reason is, that implementing the proposed logic on top of gomponents is most likely the same work and adds nothing but an extra layer of abstraction. 

Thank you for the great project @markuswustenberg , i god a lot of inspiration from it.

**Comment by markuswustenberg** [comment]
I'm happy you found a solution, @tbe. 😊
