### ISSUE TITLE
Remove fmt.Stringer support?

### ISSUE THREAD

**Issue by markuswustenberg** [maragudk/gomponents#157]
I've never liked that the error is ignored.

**Comment by eduardolat** [comment]
Now I agree with this 😅

**Comment by amrojjeh** [comment]
https://pkg.go.dev/strings#Builder.Write

I don't think that's a problem. The `Write` method is guaranteed to return `nil`

**Comment by markuswustenberg** [comment]
@amrojjeh ah, that's why! I wondered, because I don't usually just ignore errors. :D Maybe I should add a comment there.

Anyway, I think I'll close this. I think it's fine to have this.
