### ISSUE TITLE
Proposal to Add String Rendering Method to Node Interface

### ISSUE THREAD

**Issue by eduardolat** [maragudk/gomponents#164]
Hello,

I've been working with gomponents and I really appreciate the flexibility and power it brings to Go-based web development. Recently, I noticed a change in the rendering process that shifted from returning a rendered string directly:

```go
renderedString := page.Render()
```

to utilizing an io.Writer for rendering:

```go
w := bytes.Buffer{}
err := page.Render(&w)
```

This change, introduced in [PR #39](https://github.com/maragudk/gomponents/pull/39), optimizes the rendering process for different use cases. However, I find myself missing the convenience of directly obtaining the rendered output as a string for certain scenarios where working with a string is more suitable than dealing with io.Writer.

To address this, I propose adding a String() method to the Node interface, allowing users to easily obtain the rendered output as a string. This addition will improve usability by offering an alternative way to access rendered content. The proposed interface change would look like this:

```go
type Node interface {
    Render(w io.Writer) error
    String() string
}
```

The String() method could internally utilize the existing Render method with a bytes.Buffer, then return the buffer's content as a string, offering a straightforward and efficient implementation.

I am more than willing to take on the implementation of this feature if you agree with this proposal. I believe this enhancement will make gomponents even more versatile and user-friendly.

Thank you for considering my suggestion. I look forward to hearing your thoughts and am ready to contribute to making this improvement a reality.

**Comment by markuswustenberg** [comment]
Hi @eduardolat, thank you for the issue!

The `NodeFunc`, which is the function that renders an element in `El`, already satisfies the `fmt.Stringer` interface: https://github.com/maragudk/gomponents/blob/main/gomponents.go#L58

So you can do something like using `fmt.Sprint` to render your nodes to a string: https://go.dev/play/p/c-nSNHUKaAH

**Comment by eduardolat** [comment]
Thank you for your kind response.

Indeed I have realized that `NodeFunc` does satisfy the interface, however it is a bit counterintuitive that `Node` does not do it.

Is there any reason why `Node` doesn't have that method?

It would be very easy to simply do a `mypage().String()` which can easily suggested by the code editor instead of checking the code in the repository to see how it is implemented and notice that there is a `NodeFunc` function that does the task.

It is also not so intuitive due to the fact that you are always working with `Node` and not with `NodeFunc`, so you usually do not have knowledge of this function.

Would it be a good idea to add `.String()` to `Node`?
Or is it better to document `NodeFunc` and leave `Node` as is?

I leave you a couple of examples of how it is not intuitive to render as a string.

![Screenshot 2024-02-11 170331](https://github.com/maragudk/gomponents/assets/57238554/726d748b-c357-4755-8b6d-1df9fb61a67e)
![Screenshot 2024-02-11 165316](https://github.com/maragudk/gomponents/assets/57238554/0f133f90-7379-4908-bd22-a1a98a2e2d28)

Thanks for your time!!

**Comment by markuswustenberg** [comment]
I think of it this way: The only thing that is required for a component to be able to render is to satisfy the `Node` interface. Implementations of that interface, such as `NodeFunc`, may also satisfy the `fmt.Stringer` interface, but that's up to the concrete implementation.

If someone writes a large component where it wouldn't make sense to keep the whole thing in RAM (say, a large HTML document or a complex SVG), I don't want to force it on them to implement a `String() string` function. I like the streaming-based design that `io.Writer` offers. I think it's quite Go-idiomatic.

So while I think I understand what you mean, I don't want to add anything to the `Node` interface at this point. I would suggest you write a helper function for your own purposes that takes any `Node` and uses a `strings.Builder` to create a string.

I hope this makes sense. 😊

**Comment by eduardolat** [comment]
It makes all the sense in the world, now I am very clear about your decision to do it that way, I will continue to happily use my helper when I need it.

Thank you very much for this great project.

**Comment by markuswustenberg** [comment]
I’m glad to hear that. 😊
