### ISSUE TITLE
Label can be an attribute as well

### ISSUE THREAD

**Issue by Hendrikto** [maragudk/gomponents#168]
In addition to the `label` element, there is also the `label` attribute ([e.g. on the `option` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option)).

Gomponents currently [only supports the element](https://github.com/maragudk/gomponents/blob/b33f84310916b238af0006fb151a4b980721bc33/html/elements.go#L162), not the attribute. I think this should be changed.

It could be handled the same way `data`, `form`, `style`, and `title` are, by splitting it into `LabelEl` and `LabelAttr`. The only problem I see is that this would break existing code.

What do you think, Markus?

**Comment by markuswustenberg** [comment]
Hi @Hendrikto, thank you for the issue!

D'oh, I thought I had found them all. Damn. The `label` element is used extensively in a lot of code, I'll have to think about how to handle this one. Maybe there's a `go fix` type thing that could be used to fix it automatically in people's code. Hmm.

If you need it in the meantime, you can always use `g.Attr("label")`.

**Comment by markuswustenberg** [comment]
See also #170 .
