### ISSUE TITLE
Drop support for pre Go 1.18?

### ISSUE THREAD

**Issue by markuswustenberg** [maragudk/gomponents#184]
Go 1.17 is nearly three years old, and it might be nice to drop support for it and preceding versions before v1.

If anyone has objections or other comments, please leave a comment on this issue.

**Comment by GodGavin** [comment]
Why?

**Comment by markuswustenberg** [comment]
Mostly so I can drop support for the weird `Map` from pre-1.18.

**Comment by EwenQuim** [comment]
From https://go.dev/doc/devel/release

> Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release.

If even the Go team has dropped support for version 1.18, there's no reason why any library maintainer should support it.
