### ISSUE TITLE
Perhaps  we can take inspiration from 

### ISSUE THREAD

**Issue by GodGavin** [maragudk/gomponents#186]
Perhaps  u can take inspiration from below:

I believe that WebUI technical concepts in the direction of web GUI development is aimming to render HTML and corresponding DOM manipulation functions without using JavaScript, by combining backend languages with HTML. Currently, since only JavaScript can control the DOM on the browser side, such as  Blazor ， it use dedicated JavaScript libraries (Blazor.js) as DOM updaters,so u can write only one language.
This is undoubtedly a more advanced technology.
By the way, wasm is in very fast development:
After the [MVP](https://www.wasm.com.cn/docs/mvp/), to realize the [high-level goals](https://www.wasm.com.cn/docs/high-level-goals/) of (1) integrating well with the existing Web platform and (2) supporting languages other than C++, WebAssembly needs to be able to:
reference DOM and other Web API objects directly from WebAssembly code;
call Web APIs (passing primitives or DOM/GC/Web API objects) directly from WebAssembly without calling through JavaScript.
Maybe in that day,we can only use backend language to do perfect webui

In my view, It would be beneficial to directly learn from some tech like Blazor’s approach.

**Comment by GodGavin** [comment]
@markuswustenberg

**Comment by markuswustenberg** [comment]
I don't understand what this issue is about. Could you elaborate what it has to do with gomponents? The links point to sites with languages I can't read. :)

**Comment by GodGavin** [comment]
how about this way below,blazor 'approach
https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/try

**Comment by markuswustenberg** [comment]
Okay, so Blazor seems to be about writing in backend languages in the frontend? gomponents aims to be pretty simple and just render HTML strings, so I think that's outside the scope of the project.

**Comment by markuswustenberg** [comment]
HTML has been working great alone for literally decades. I think I'll close this issue now.
