### ISSUE TITLE
JS Ternary like

### ISSUE THREAD

**Issue by TudorHulban** [maragudk/gomponents#187]
hi,
thank you for the nice library!

please advise if a javascript ternary like option exists in roadmap or could be implemented as
```go
func Ternary(condition bool, n1, n2 Node) Node {
	if condition {
		return n1
	}

	return n2
}
```

**Comment by markuswustenberg** [comment]
Hi @TudorHulban , thank you for the issue!

Unfortunately I don't really want to increase the API surface area more than necessary, and I would consider something like this more a nice-to-have than need-to-have. I would suggest you maybe add it to a module you control and just use that. 😊
