### ISSUE TITLE
Move gomponents module to maragu.dev/gomponents

### ISSUE THREAD

**Issue by markuswustenberg** [maragudk/gomponents#200]
I want to be independent of Github and move the module to my own namespace.

This will obviously be a breaking change, so I want to make it the least painful possible. Investigate how.

**Comment by EwenQuim** [comment]
This makes users dependent on your domain name.

**Comment by markuswustenberg** [comment]
@EwenQuim yes, but the code is still available on Github. So if anything happens to me and/or the domain, the project can just be forked. 😊

**Comment by markuswustenberg** [comment]
Also, I realized that the Go module proxy makes sure that the module will always be available, even if the domain and/or repo is down, so I think I'm going to do this before v1.
