### ISSUE TITLE
Map-like function that passes the item index in the callback

### ISSUE THREAD

**Issue by deitrix** [maragudk/gomponents#208]
Like, how `Map` takes a callback `func(T) Node`, would you be open to adding a `MapIndex`, or `MapI` to the library that passes the item index in the callback?

```go
// MapIndex is like [Map], but also passes the index of the item to the callback.
func MapIndex[T any](ts []T, cb func(int, T) Node) []Node {
	var nodes []Node
	for i, t := range ts {
		nodes = append(nodes, cb(i, t))
	}
	return nodes
}
```

**Comment by markuswustenberg** [comment]
Some history: I added `Map` before generics in Go were a thing, and I'm not sure I would do this now, since any generics-capable function can basically map anything to `Node`s.

For that reason, I would lean towards not including something like this, since I would expect a function like this to be available either in a widely used library, or even the stdlib at some point.

Thoughts?

**Comment by deitrix** [comment]
I don't disagree that something like that should be readily available, though I'm not so sure it is, given new changes in https://github.com/maragudk/gomponents/pull/202.

https://github.com/samber/lo has a lot of generic utilities like this, but I don't think any of them would be as ergonomic is a first-class utility.

If the changes in https://github.com/maragudk/gomponents/pull/202 are introduced, the only two options I can think of are using `lo.Map` and casting to a `Group`, or using `lo.Reduce` to build up a `Group`, neither of which are particularly pretty solutions.

using `lo.Map`
```go
vals := []int{1, 2, 3, 4, 5}

elem := Group(lo.Map(vals, func(item int, index int) g.Node {
	return Div(g.Textf("item %d: %d", index, item))
}))
```
using `lo.Reduce`
```go
elem := lo.Reduce(vals, func(agg Group, item int, index int) Group {
	return append(agg, Div(g.Textf("item %d: %d", index, item)))
}, Group{})
```

With this library being almost akin to JSX, but in Go, I don't think it's unreasonable to expect a batteries included approach that lets you do all the things you'd be able to do in JSX; I don't like the idea of introducing another third-party dependency just for this 😢

However, I understand your reservations. There probably exists 1000 different (yet similar) implementations of `Map` across the Go ecosystem 😅 Maybe I'll just stick with keeping these sorts of utilities local to my projects, for now.

**Comment by markuswustenberg** [comment]
I see myself as a gatekeeper for feature creep, so I'm always wary to introduce new functionality without properly vetting the idea first. That said, I'm open to adding this if indeed it's useful to people.

What's the use case? I've never had the need myself.

**Comment by deitrix** [comment]
My use case is form construction. I have a form with a dynamic number of elements, and I need the numeric index to determine the form input name/ids. I could always wrap my type in a container type, which includes the index, but I feel that's a little awkward 😄

**Comment by markuswustenberg** [comment]
What about a closure solution?

```go
func ExampleMap_index() {
	items := []string{"party hat", "super hat"}
	var index int
	e := g.El("ul", g.Map(items, func(i string) g.Node {
		e := g.El("li", g.Textf("%v: %v", index, i))
		index++
		return e
	}))
	_ = e.Render(os.Stdout)
	// Output: <ul><li>0: party hat</li><li>1: super hat</li></ul>
}
```

And of course it's always possible to have small private functions that copy around from project to project on an as-needed basis. I often do that for all kinds of small utilities.

I'm also toying with the idea of somehow adding the functionality to the existing `Map` without breaking anything, but not sure what kind of shenanigans that takes yet.

**Comment by markuswustenberg** [comment]
I'm going to close this one, I think the closure solution is okay. If this keeps coming up from other sources, I'm open to revisiting the choice. No matter what, thank you for the feedback!
