### ISSUE TITLE
Create a gomponents + HTMX + TailwindCSS sample repo

### ISSUE THREAD

**Issue by markuswustenberg** [maragudk/gomponents#213]

**Comment by glsubri** [comment]
Hey @markuswustenberg 👋

First of all, thanks for gomponents. I really enjoy using it.

I'm currently building a small app using that stack exactly. I could probably share/modify some parts of what I'm doing and set up an example repo if that's of any help.

Did you want to do this yourself or are you happy if someone takes that out of your plate ?

**Comment by markuswustenberg** [comment]
@glsubri first of all, thank you a lot! 😊

I basically also have something like this already, it just needs to be trimmed to an example app. And I want to make sure it uses the soon-to-be new import paths at `maragu.dev`, so:
- `maragu.dev/gomponents`
- `maragu.dev/gomponents-htmx`

I haven't gotten around to actually creating the second one yet.

I want to make sure I don't waste your time in accepting your offer, that would make us both sad. Would you be open to starting the repo and accepting contributions from me?

**Comment by markuswustenberg** [comment]
And I'm super happy you enjoy it! 😊

**Comment by glsubri** [comment]
> @glsubri first of all, thank you a lot! 😊
> 
> I basically also have something like this already, it just needs to be trimmed to an example app. And I want to make sure it uses the soon-to-be new import paths at `maragu.dev`, so:
> 
> * `maragu.dev/gomponents`
> * `maragu.dev/gomponents-htmx`
> 
> I haven't gotten around to actually creating the second one yet.
> 
> I want to make sure I don't waste your time in accepting your offer, that would make us both sad. Would you be open to starting the repo and accepting contributions from me?

I don't know why I initially thought it would be only a directory containing the example app. I don't mind creating a new repo, but maybe it makes more sense if it's yours. (I feel like people may be confused if the example app is in my repos)

Maybe we can do this the other war around. Having a dedicated repo for examples and subdirectories for different apps?

**Comment by markuswustenberg** [comment]
Good point. I don't want it inside this repo directly, as I think it creates too much noise in the git log that is not related to the core library. But I created the gomponents-gallery repo recently, I think it could fit quite well there (with a new go.mod file in a subdirectory somewhere): https://github.com/maragudk/gomponents-gallery

**Comment by markuswustenberg** [comment]
I think I'm going to try this tomorrow. Thinking that maybe a separate repo makes sense after all, so people can use the GitHub template repo functionality. Thoughts?

**Comment by markuswustenberg** [comment]
@glsubri I created https://github.com/maragudk/gomponents-starter-kit . Could you maybe give it a spin if you have the time? The easiest way would be to use Github's built-in template repository functionality: https://github.com/new?template_name=gomponents-starter-kit&template_owner=maragudk

**Comment by glsubri** [comment]
@markuswustenberg I'll take a look this week 👍
