### ISSUE TITLE
Investigate supporting `Render(context.Context, io.Writer) error`

### ISSUE THREAD

**Issue by markuswustenberg** [maragudk/gomponents#219]
Suggested by the article mentioned in #218.

**Comment by markuswustenberg** [comment]
@EwenQuim could you elaborate what this means? How would you use it?

The way I build components, they look like this:

```go
func SomeComponent(ctx SomeContext) Node {
    return Div(Span(ctx.Whatever)) 
}
```

In that case, I can pass whatever to it in `SomeContext`, or other parameters. When would you need the `context.Context` at render time?

**Comment by amrojjeh** [comment]
The main argument that's provided for this request is to simplify implementing both Templ and Gomponents, but I personally don't see why this would be done at all, and even if it is, there's no friction as you'd just call the appropriate `Render` function and pass the required parameters. Any further needed abstractions can be made by the user as per the project requirements

**Comment by EwenQuim** [comment]
As Adrien said :

Gomponent to Templ conversion

```go
type Gomponent interface {
  Render(w io.Writer) error
}

func ToTempl(g Gomponent) templ.Component {
  func templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
     return g.Render(w)
  })
}
```


Templ to Gomponent conversion

```go
type gomp struct {
   c templ.Component
}

func (g gomp) Render(w io.Writer) error {
  return g.c.Render(context.Background(), w)
}

func ToGomponent(c templ.Component) Gomponent {
  return g{c: c}
}
```

**Comment by markuswustenberg** [comment]
Thanks for your input @amrojjeh and @EwenQuim. I'll just close the issue. 😊
