### ISSUE TITLE
Implementing fmt.Stringer as a convenience 

### ISSUE THREAD

**Issue by emad-elsaid** [maragudk/gomponents#230]
Would it make sense to `Node` to implement `fmt.Stringer` interface as a convenience for users? so Nodes can be converted to string 

```go
Div(String("Hello world")).String()
```

Also can be used as HTML type 
```go
template.HTML(Div(String("Hello world")).String())
```

**Comment by markuswustenberg** [comment]
Hi @emad-elsaid, thank you for the issue. 

This has actually been discussed before, see issue #164. 😊
