### ISSUE TITLE
Using gomponents to create custom reactive elements

### ISSUE THREAD

**Issue by mrzapp** [maragudk/gomponents#63]
First of all, very neat project!

I was thinking of a use case that I couldn't find any information on.

Let's say I wanted to create custom elements with event handlers, like I'd be able to in JavaScript using Web Components. In client-side code, I'd create a class that extends HTMLElement, register it and hook up some event handlers in the constructor. This is fairly handy, but it does mean I'd still have to write controllers for REST or WebSocket connections.

Using this project, I'm fantasising about being able to declare a custom "gomponent", write event handlers server side and trigger them via either WebSocket or REST from the client. This way you'd really have your entire behaviour in one class and not segmented across markup, client-side code and server-side code.

Are there any plans to implement something like this?

**Comment by markuswustenberg** [comment]
Hej @mrzapp. 😊

The short answer is: no.

This is purely a server-side rendering library. Handling anything client-side or communication between server and client is outside the scope of the project.

Maybe something like https://hotwire.dev would be of interest to you.

**Comment by mrzapp** [comment]
Hotwire looks pretty dang cool too, thanks for the tip.
