### ISSUE TITLE
Support Template interface

### ISSUE THREAD

**Issue by yuriizinets** [maragudk/gomponents#70]
Hey there!
As a creator of [go-ssc](https://github.com/yuriizinets/go-ssc) library, I'm really excited to see alternative opinion and approach. This library does not solve the problems I described in go-ssc, but it's very interesting in terms of templating. That's why I wanna to try to combine our approaches. I'm thinking about providing support of different template engines. Is there any chance that gomponents will implement Template interface in the future?

**Comment by markuswustenberg** [comment]
@yuriizinets I've had a brief look at your library. As I understand it right now, it doesn't really make sense for me to have anything to do with `html/template`. I'm not using that package anywhere in the gomponents code, and I'm not really sure what it would do?

Could you give a (pseudo-) code example on what you mean by implementing the `Template` interface?
