### ISSUE TITLE
Potential XSS: Values passed to Attr(...) are not escaped by default

### ISSUE THREAD

**Issue by philippta** [maragudk/gomponents#74]
Currently values passed to the `Attr(name, value)` function are not escaped during rendering by default and impose a potential security risk. These values should be treated as unsafe data, like any other data rendered with the `Text(...)` function.

### Example
```go
Div(g.Attr("foo", `bar" baz="`)).Render(os.Stdout)
```
```html
<!-- Current behavior -->
<div foo="bar" baz=""></div>

<!-- Expected behavior -->
<div foo="bar&#34; baz=&#34;"></div>
```

### Why is this important?

In most cases html attribute like `class="navbar"`, `id="cta-button"`, `name="email"` are statically defined by the developers and do not impose much risk.

However when rendering user supplied data in e.g. a _change profile_ page a user could escape the html attributes by choosing a name like: `Little Bobby"> Tables` which then leads to a potential XSS.

#### Insecure Example
```go
func InputField(name, defaultValue string) g.Node {
    return Input(Name(name), Value(defaultValue)) // calling Attr(...)
}

InputField("firstname", `Little Bobby"> Tables`).Render(os.Stdout)
```

```html
<input name="firstname" value="Little Booby"> Tables">
```

## Proposal

1. Escape all values passed to `Attr(name, value)` by default. (This will _and should_ also affect all other attribute helper functions)
2. Introduce a second, insecure function e.g. `AttrRaw(name, rawvalue)`

## cf.
The `html/template` package has a whole range of escaping functions, including one for [html attributes](https://github.com/golang/go/blob/b38b1b2f9ae710ee2c16a103bb21644f1adbc5d3/src/html/template/escape.go#L63).

**Comment by markuswustenberg** [comment]
Hi @philippta . First of all, thank you for your detailed issue description! This is great, and I value it a lot. 😊

I've been thinking about this as well, and also saw your comment on Reddit about something similar. I agree that it's really cool that `html/template` does this automatically. But I can't really decide whether this is something I should include as well or not. 

As you mention yourself, in most cases attributes are defined by developers and not based on data from elsewhere, and I find that it would perhaps make the API more confusing if I were to introduce different helpers for escaping e.g. attribute values. But I definitely see your point that the current implementation is unsafe in certain threat models. Of course, I could make the default implementation safe against XSS, but I think I'd like to think about the implications about that first. I lean towards making safe the default, though.

Do you have any input on whether this should apply in more places? For example, should I have a special helper for inline styles, that safely escapes CSS? What about `script` blocks? I'm really in doubt about the best approach here.

And again, thank you again for your issue, it's really appreciated.

PS: Love the XKCD reference. 😁

**Comment by philippta** [comment]
Hey @markuswustenberg, 

I think the best approach would be to escape any data inserted to the `g.Attr` function, the value aswell as the name, because both can lead to a XSS vuln. I can't think of a valid use case where a developer would intentionally want to break out of the attribute context. And if so, there is always `g.Raw`. 

## Style, Script, Inline Style
You asked if this should apply to more places like inline styles or script tags.

**Script and style tags:**
I would suggest that style and script *tags* (`StyleEl`, `Script`) should not be effected by escaping because it's pretty clear that the passed value is similar to the `g.Raw` element. Otherwise, if the whole content of those tags would be escaped the entire thing would not function at all.

**Inline style:**
Inline style tags are a bit different as they are not trivial to handle. The `html/template` escaper for inline styles behaves differently than other tags, as it would both have to take into account the html escaping and also parse the css to block things like: `<div style="background: url('javascript:alert(1)';">`. I'm not entirely sure what's the best approach for this, but default html escaping (`&`,`<`, `>`, `"`, `'`) would be a low hanging fruit to start with.

 ## Implications

From the top of my head, I see no bad implications for this change. One thing to note is, that some characters would be represented in their `&#XX;` form (e.g. `<div foo="bar=&#34;baz&#34;">`), which looks like an error. **But it's not.** The browser and the javascript engine will parse this correctly and render the correct characters. You can see this here: https://jsfiddle.net/getL2q15/

## General advice from OWASP
The [OWASP cheat sheet](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html) gives a pretty good overview where untrusted data must be avoided. It also defines what characters must be escaped in order to prevent XSS.

> Directly in a script:
> ```html
> <script>...NEVER PUT UNTRUSTED DATA HERE...</script>
> ```
> 
> Inside an HTML comment:
> ```html
> 
> ```
> 
> In an attribute name:
> ```html
> <div ...NEVER PUT UNTRUSTED DATA HERE...=test />
> ```
> 
> In a tag name:
> ```html
> <NEVER PUT UNTRUSTED DATA HERE... href="/test" />
> ```
> 
> Directly in CSS:
> ```html
> <style>
> ...NEVER PUT UNTRUSTED DATA HERE...
> </style>
> ```

**Comment by markuswustenberg** [comment]
Before I get to answering the content: wow, I appreciate the detail and effort you've put into this. 🙏 I'll get back to it soon.

**Comment by markuswustenberg** [comment]
@philippta Just a quick note: I haven't gotten around to getting your latest comment incorporated yet, but it's not forgotten. 😊

**Comment by markuswustenberg** [comment]
@philippta Okay, I've spent some time thinking about this. I will change the PR to not escape the attribute name, I think that makes the most sense. So I agree with your option 2.

**Comment by markuswustenberg** [comment]
By the way, I've also reverted escaping tag names, for the same reason as attribute names: I consider it unlikely that a major use case is to put user-supplied data into tag names.

@oderwat suggested panicking on bad tag names and attribute names. I will think about that a bit as well, and maybe implement that in a separate PR. I'm leaning towards not doing that, however.

**Comment by oderwat** [comment]
I actually didn't mean to `panic()` the whole app. I also wrote a template engine a long time ago which is used by multiple projects. There I use a "warning" mechanism that corrects wrongdoings in the most "unharmful" way (like mangling the tag-name so it becomes technically valid) and at the same time register a warning. Those warnings go into some live logging on the servers and so we can check the whole system for unexpected "strange things" happening.

**Comment by markuswustenberg** [comment]
@oderwat ah, right. Yeah, that's definitely a possibility. But it makes the whole library more complex, so I'm not sure what the best approach is yet. I'll have to think about that for a while. Thanks for the feedback!
