### ISSUE TITLE
Use with TailwindCSS JIT

### ISSUE THREAD

**Issue by Alexfilus** [maragudk/gomponents#78]
Hi! There is any way to connect gomponents with TailwindCSS JIT? It should be very lightweight and useful.

**Comment by markuswustenberg** [comment]
@Alexfilus I think that's definitely doable. I haven't tried it myself yet, but if you like you could try enabling jit on https://github.com/maragudk/gomponents-tailwind-example and report back?

Note that the repo hasn't been updated in a while, I might have some time to do that soon.

**Comment by markuswustenberg** [comment]
@Alexfilus I've updated the example project with the JIT compiler. I hope you find it useful. 😊 See https://github.com/maragudk/gomponents-tailwind-example
