### ISSUE TITLE
picture & img element improvements

### ISSUE THREAD

**Issue by averageflow** [maragudk/gomponents#85]
Hi @markuswustenberg , I am really happy that I discovered your project here and I am excited to put it to good use and bring it to production for several of my clients.
I love Go, compiled language, type safety and the great re-usability that we get by using Go components.
I can only see one spot where some love is missing, and that is in the image elements.

I particularly make heavy use of the `picture` element and the `img` element in some sites. Some points I have noticed are:
- Missing `srcset` attribute in `picture` element
- Missing `loading` attribute in `img` element

With those 2 additions I can really bring this to all my current and future projects. If you don't have the time to implement this, I would also not mind tips on how to proceed adding this to the codebase, although I would be a bit lost and it would take some time.

Thanks in advance man! And thanks for this wonderful creation!
Greetings from NL 🇳🇱

**Comment by markuswustenberg** [comment]
@averageflow I'd be happy to add the attributes. 😊 Cool that you figured it out on your own. I'll have a look at #86 and probably merge it very soon. Thank you for your contribution!

**Comment by markuswustenberg** [comment]
@averageflow this is now part of v0.17.2.

**Comment by averageflow** [comment]
🤟🏼 awesome @markuswustenberg

**Comment by markuswustenberg** [comment]
Btw if you didn't know already: you can always use the `g.Attr` function if there's ever an attribute there isn't a helper for yet, so you don't have to wait for a fix. The same with `g.El` for elements. 😊

**Comment by averageflow** [comment]
@markuswustenberg that is really a good one! I will see if I can allocate some time (maybe during work hours haha) to write some documentation for the project. 
I truly am a fan! Thanks man :)

**Comment by markuswustenberg** [comment]
> @markuswustenberg that is really a good one! I will see if I can allocate some time (maybe during work hours haha) to write some documentation for the project.

Yeah, I guess I could mention that on www.gomponents.com. It's always a tradeoff with details vs. too much information for beginners. But it's in the go doc: https://pkg.go.dev/github.com/maragudk/gomponents#Attr

> I truly am a fan! Thanks man :)
Good to hear. 😊 Spread the word!
