### ISSUE TITLE
Consider whether generics can make the API clearer

### ISSUE THREAD

**Issue by markuswustenberg** [maragudk/gomponents#88]
…and if it's worth breaking backwards compatibility for it.

**Comment by dimiro1** [comment]
The Map function could be generic, something  like this.

```go
func Map[T any](elements []T, predicate func(elem T) Node) []Node
```

**Comment by markuswustenberg** [comment]
> The Map function could be generic, something like this.
> 
> ```go
> func Map[T any](elements []T, predicate func(elem T) Node) []Node
> ```

Yeah, that's probably the best contender. I don't think I'm going to do anything with generics before at least Go 1.19, to see how the stdlib evolves first.

**Comment by markuswustenberg** [comment]
Done to the extent I think is good, for now.
